// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOPA54PQda8thYwgX1-xKTNClVMJRoF0Y',
    appId: '1:210164140219:web:9c0b67847aa65fb647019e',
    messagingSenderId: '210164140219',
    projectId: 'aygflutter',
    authDomain: 'aygflutter.firebaseapp.com',
    storageBucket: 'aygflutter.appspot.com',
    measurementId: 'G-FJMWEF1285',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwqCrQTK3LqRz2QjwSibCwy7901gH_6UI',
    appId: '1:210164140219:android:097852811bc66b2347019e',
    messagingSenderId: '210164140219',
    projectId: 'aygflutter',
    storageBucket: 'aygflutter.appspot.com',
  );
}
